### WINDOW ###
GAME_TITLE = "Laptop NoPixel"

SCREEN_WIDTH = 1100
SCREEN_HEIGHT = 600
WINDOW_POS_LEFT = 200
WINDOW_POS_TOP = 200

### UNIT ###
UNIT_NUMBER = 4
UNIT_COLORS = ["WHITE", "RED", "GREEN", "BLUE", "YELLOW", "ORANGE", "PURPLE", "BLACK"]
UNIT_SHAPES = ["RECTANGLE", "TRIANGLE", "CIRCLE", "SQUARE"]

BACKGROUND_SQUARE_SIDE = int(SCREEN_WIDTH / (UNIT_NUMBER + 1))
CIRCLE_RADIUS = int(BACKGROUND_SQUARE_SIDE / 3)
TRIANGLE_SIZE = int(BACKGROUND_SQUARE_SIDE / 3)
SQUARE_SIDE = int(BACKGROUND_SQUARE_SIDE / 3 * 2)
GAP_SIZE = int(BACKGROUND_SQUARE_SIDE / (UNIT_NUMBER + 1))

### FONT ###
FONT_TYPE = "Times New Roman"
HUGE_TEXT_SIZE = int(SCREEN_WIDTH / 8)
LARGE_TEXT_SIZE = int(SCREEN_WIDTH / 16)
MEDIUM_TEXT_SIZE = int(SCREEN_WIDTH / 32)
SMALL_TEXT_SIZE = int(SCREEN_WIDTH / 40)

### GAME ###
START_TIME = 23000
SOLVE_TIME = 112000

GAME_COLORS = {
    "WHITE": (255, 255, 255),
    "RED": (123, 1, 0),
    "GREEN": (76, 174, 79),
    "BLUE": (33, 149, 238),
    "YELLOW": (255, 235, 61),
    "ORANGE": (253, 152, 2),
    "PURPLE": (153, 38, 172),
    "BLACK": (0, 0, 0),
    "BACKGROUND": (32, 40, 46),
    "SQUARE_BACKGROUND": (46, 69, 97),
    "LIGHT_ORANGE": (244, 169, 107),
    "DARK_ORANGE": (90, 56, 23),
}
